# Generated by Django 5.1.1 on 2024-10-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0002_remove_user_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="level_name",
            field=models.CharField(default="Seeker of Truth", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="level_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="welcome_bonus",
            field=models.BooleanField(default=False),
        ),
    ]
