# Generated by Django 5.1.1 on 2024-10-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_user_balance_user_level_name_user_level_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_number", models.PositiveIntegerField(default=1)),
                ("level_name", models.CharField(max_length=100)),
                ("lower_points", models.PositiveBigIntegerField()),
                ("higher_points", models.PositiveBigIntegerField()),
                ("per_tap", models.PositiveIntegerField()),
                ("point_refill", models.PositiveIntegerField()),
                ("number_of_tap", models.PositiveIntegerField()),
            ],
        ),
    ]
