# Generated by Django 5.1.1 on 2024-10-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0005_earnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="multitap_level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="recharging_speed_level",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
