# Generated by Django 5.1.1 on 2024-10-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0006_user_multitap_level_user_recharging_speed_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="autobot_status",
            field=models.BooleanField(default=False),
        ),
    ]
