# Generated by Django 5.1.1 on 2024-10-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0007_user_autobot_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[("daily", "Daily"), ("social", "Social")],
                        max_length=10,
                    ),
                ),
                ("points", models.PositiveIntegerField()),
            ],
        ),
    ]
