# Generated by Django 5.1.1 on 2024-10-23 09:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0009_usertaskclaim"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
