# Generated by Django 5.1.1 on 2024-10-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0012_usercardclaim"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="action",
            field=models.CharField(
                choices=[("join", "Join"), ("visit", "Visit")],
                default="visit",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tasks"),
        ),
        migrations.AddField(
            model_name="tasks",
            name="is_telegram",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tasks",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
