# Generated by Django 5.1.1 on 2024-10-28 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0013_tasks_action_tasks_image_tasks_is_telegram_tasks_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cards",
            name="points",
        ),
        migrations.CreateModel(
            name="CardsDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level_number", models.PositiveIntegerField(default=0)),
                ("burning_points", models.PositiveIntegerField()),
                ("automine_points", models.PositiveIntegerField()),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards_details",
                        to="user_app.cards",
                    ),
                ),
            ],
        ),
    ]
