# Generated by Django 5.1.1 on 2024-10-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0014_remove_cards_points_cardsdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="cards",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cards",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cards"),
        ),
    ]
