# Generated by Django 5.1.1 on 2024-12-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_dailyreward_userdailyreward_boosterclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_religion',
            field=models.CharField(blank=True, choices=[('Islamic', 'Islamic'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity'), ('Sikhism', 'Sikhism'), ('Judaism', 'Judaism'), ('Hindu', 'Hindu'), ('Mothernature', 'Mother Nature'), ('Unaffiliated', 'Unaffiliated')], max_length=50, null=True),
        ),
    ]
