# Generated by Django 5.1.1 on 2025-01-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_user_user_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('social', 'Social'), ('partner', 'Partner')], max_length=10),
        ),
    ]
