# Generated by Django 5.1.1 on 2025-02-10 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0018_alter_tasks_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="tasks"
            ),
            preserve_default=False,
        ),
    ]
